version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: taskdb
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskpass
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=mysql
      - DB_USER=taskuser
      - DB_PASSWORD=taskpass
      - DB_NAME=taskdb
      - JWT_SECRET=supersecretkey123
    ports:
      - "4000:4000"
    depends_on:
      - mysql
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:80"
    depends_on:
      - backend
volumes:
  dbdata:
